import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/custom/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Augustine Chukwuemeka Portfoilo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col lg:flex-row max-w-screen-2xl mx-auto min-h-screen border-x bg-black border-gray-400/25`}
      >
        <Navbar />
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
